"use client";

import { useMemo, useState, type FormEvent } from "react";
import { CalendarClock, CheckCircle2, Download, FileText, Mail, Pause, Play, Plus, Printer, Settings2, ShieldCheck, Trash2 } from "lucide-react";
import { jsPDF } from "jspdf";
import Modal from "../../Components/Modal";
import TablePagination, { useTablePagination } from "../../Components/TablePagination";
import useDemoState from "../../Components/useDemoState";
import type { Employee, PayrollRun, PayrollView } from "./PayrollPage";

type ControlView = Exclude<PayrollView, "dashboard" | "employees" | "runs" | "attendance">;
type Schedule = { id: string; name: string; frequency: "Weekly" | "Bi-weekly" | "Semi-monthly" | "Monthly"; periodStart: string; periodEnd: string; payday: string; active: boolean };
type Benefit = { id: string; name: string; employeeId: string; kind: "Deduction" | "Benefit" | "Allowance"; employeeAmount: number; employerAmount: number; recurring: boolean; active: boolean };
type PayrollSettings = { defaultSchedule: string; overtimeMultiplier: number; taxRate: number; payslipNote: string; requireApproval: boolean; approvalLimit: number };
type PayrollAudit = { id: string; date: string; actor: string; action: string; record: string };

const initialSchedules: Schedule[] = [
  { id: "SCH-1", name: "Monthly team payroll", frequency: "Monthly", periodStart: "2026-08-01", periodEnd: "2026-08-31", payday: "2026-08-31", active: true },
  { id: "SCH-2", name: "Monthly management payroll", frequency: "Monthly", periodStart: "2026-08-01", periodEnd: "2026-08-31", payday: "2026-08-31", active: true },
  { id: "SCH-3", name: "Bi-weekly production payroll", frequency: "Bi-weekly", periodStart: "2026-08-18", periodEnd: "2026-08-31", payday: "2026-09-03", active: false },
];
const initialBenefits: Benefit[] = [
  { id: "BEN-1", name: "Employee advance", employeeId: "emp-1", kind: "Deduction", employeeAmount: 80, employerAmount: 0, recurring: true, active: true },
  { id: "BEN-2", name: "Transport allowance", employeeId: "all", kind: "Allowance", employeeAmount: 65, employerAmount: 0, recurring: true, active: true },
  { id: "BEN-3", name: "Health support", employeeId: "emp-3", kind: "Benefit", employeeAmount: 0, employerAmount: 120, recurring: true, active: true },
];
const initialSettings: PayrollSettings = { defaultSchedule: "Monthly team payroll", overtimeMultiplier: 1.5, taxRate: 7.5, payslipNote: "Thank you for your work at Ora Dental Laboratory.", requireApproval: true, approvalLimit: 2500 };
const initialAudit: PayrollAudit[] = [
  { id: "AUD-1", date: "2026-08-12T10:15:00", actor: "Hassan", action: "Payroll run moved to review", record: "PAY-2026-08" },
  { id: "AUD-2", date: "2026-08-11T18:10:00", actor: "Hassan", action: "Timesheet approved", record: "Omar Khoury" },
  { id: "AUD-3", date: "2026-08-09T13:34:00", actor: "Hassan", action: "Hourly rate changed", record: "Lina Darwish" },
];

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));
const downloadCsv = (name: string, rows: Array<Array<string | number>>) => { const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); };

function Heading({ label, title, description, action }: { label: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="payroll-page-heading"><div><span>{label}</span><h2>{title}</h2><p>{description}</p></div>{action && <div className="payroll-heading-actions">{action}</div>}</header>;
}

export default function PayrollControlPages({ view, employees, runs, onNotice }: { view: ControlView; employees: Employee[]; runs: PayrollRun[]; onNotice: (message: string) => void }) {
  const [schedules, setSchedules] = useDemoState<Schedule[]>(initialSchedules);
  const [benefits, setBenefits] = useDemoState<Benefit[]>(initialBenefits);
  const [settings, setSettings] = useDemoState<PayrollSettings>(initialSettings);
  const [audit, setAudit] = useDemoState<PayrollAudit[]>(initialAudit);
  const [modal, setModal] = useState<"schedule" | "benefit" | null>(null);
  const [selectedRun, setSelectedRun] = useState(runs.find((run) => run.status === "Paid")?.id ?? runs[0]?.id ?? "");

  const addAudit = (action: string, record: string) => setAudit((current) => [{ id: `AUD-${Date.now()}`, date: new Date().toISOString(), actor: "Hassan", action, record }, ...current]);
  const saveSchedule = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next: Schedule = { id: `SCH-${Date.now()}`, name: String(form.get("name")), frequency: String(form.get("frequency")) as Schedule["frequency"], periodStart: String(form.get("periodStart")), periodEnd: String(form.get("periodEnd")), payday: String(form.get("payday")), active: true }; setSchedules((current) => [next, ...current]); addAudit("Pay schedule created", next.name); setModal(null); onNotice(`${next.name} was created.`); };
  const saveBenefit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next: Benefit = { id: `BEN-${Date.now()}`, name: String(form.get("name")), employeeId: String(form.get("employeeId")), kind: String(form.get("kind")) as Benefit["kind"], employeeAmount: Number(form.get("employeeAmount")), employerAmount: Number(form.get("employerAmount")), recurring: form.get("recurring") === "on", active: true }; setBenefits((current) => [next, ...current]); addAudit(`${next.kind} created`, next.name); setModal(null); onNotice(`${next.name} was added to payroll.`); };

  const run = runs.find((item) => item.id === selectedRun) ?? runs[0];
  const payslips = useMemo(() => (run?.lines?.length ? run.lines : employees.filter((employee) => employee.status === "Active").map((employee, index) => { const net = Math.max(0, (run?.net ?? 0) / Math.max(1, run?.employees ?? 1) + index * 11); return { employeeId: employee.id, regularHours: 0, overtimeHours: 0, base: net / .925, overtime: 0, bonus: 0, allowances: 0, deductions: net / .925 - net, gross: net / .925, net }; })).map((line) => ({ line, employee: employees.find((employee) => employee.id === line.employeeId) })).filter((item) => item.employee), [employees, run]);
  const payslipPagination = useTablePagination(payslips, selectedRun);
  const printPayslip = (employee: Employee, line: (typeof payslips)[number]["line"], pdf = false) => { const doc = new jsPDF(); doc.setFontSize(18); doc.text("Ora Dental Laboratory", 18, 20); doc.setFontSize(12); doc.text(`Payslip - ${run?.id ?? "Payroll"}`, 18, 31); doc.setFontSize(10); [["Employee", employee.name], ["Pay period", run ? `${date(run.start)} - ${date(run.end)}` : "-"], ["Base earnings", money(line.base)], ["Overtime", money(line.overtime)], ["Allowances", money(line.allowances)], ["Gross pay", money(line.gross)], ["Deductions", money(line.deductions)], ["Net pay", money(line.net)]].forEach(([label, value], index) => { doc.text(label, 18, 48 + index * 10); doc.text(value, 92, 48 + index * 10); }); doc.text(settings.payslipNote, 18, 140); if (pdf) doc.save(`${run?.id ?? "payroll"}-${employee.name.replaceAll(" ", "-")}.pdf`); else window.open(doc.output("bloburl"), "_blank"); addAudit(pdf ? "Payslip downloaded" : "Payslip printed", employee.name); };

  if (view === "schedules") return <div className="payroll-page"><Heading label="Control" title="Pay schedules" description="Define pay periods and payday rules for each payroll group." action={<button className="primary-button" type="button" onClick={() => setModal("schedule")}><Plus size={16} />Create schedule</button>} /><section className="payroll-control-list">{schedules.map((item) => <article key={item.id}><span className="payroll-control-icon"><CalendarClock size={18} /></span><div><strong>{item.name}</strong><small>{item.frequency} · {date(item.periodStart)} to {date(item.periodEnd)}</small></div><span><small>Payday</small><strong>{date(item.payday)}</strong></span><button className={item.active ? "secondary-button compact" : "primary-button compact"} type="button" onClick={() => { setSchedules((current) => current.map((schedule) => schedule.id === item.id ? { ...schedule, active: !schedule.active } : schedule)); addAudit(item.active ? "Pay schedule paused" : "Pay schedule activated", item.name); }}>{item.active ? <><Pause size={14} />Pause</> : <><Play size={14} />Activate</>}</button><button className="icon-button danger" type="button" aria-label={`Delete ${item.name}`} onClick={() => setSchedules((current) => current.filter((schedule) => schedule.id !== item.id))}><Trash2 size={15} /></button></article>)}</section>{modal === "schedule" && <ScheduleModal onClose={() => setModal(null)} onSubmit={saveSchedule} />}</div>;

  if (view === "payslips") return <div className="payroll-page"><Heading label="Payroll" title="Payslips" description="Review earnings, deductions, net pay, and produce employee documents." action={<select className="payroll-run-select" value={selectedRun} onChange={(event) => setSelectedRun(event.target.value)}>{runs.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.status}</option>)}</select>} /><section className="payroll-table-card"><div className="finance-table-scroll"><table className="finance-table payroll-control-table"><thead><tr><th>Employee</th><th>Run</th><th>Gross</th><th>Deductions</th><th>Net pay</th><th>Actions</th></tr></thead><tbody>{payslipPagination.pageItems.map(({ employee, line }) => employee && <tr key={employee.id}><td><strong>{employee.name}</strong><small>{employee.title}</small></td><td>{run?.id}</td><td>{money(line.gross)}</td><td>{money(line.deductions)}</td><td><strong>{money(line.net)}</strong></td><td><div className="payroll-row-actions"><button className="icon-button" type="button" title="Print" onClick={() => printPayslip(employee, line)}><Printer size={15} /></button><button className="icon-button" type="button" title="Download PDF" onClick={() => printPayslip(employee, line, true)}><Download size={15} /></button><button className="icon-button" type="button" title="Queue email" onClick={() => { addAudit("Payslip email queued", employee.name); onNotice(`Payslip email queued for ${employee.name}.`); }}><Mail size={15} /></button></div></td></tr>)}</tbody></table></div><TablePagination {...payslipPagination} /></section></div>;

  if (view === "benefits") return <div className="payroll-page"><Heading label="People" title="Deductions & benefits" description="Manage recurring or one-time deductions, benefits, advances, and allowances." action={<button className="primary-button" type="button" onClick={() => setModal("benefit")}><Plus size={16} />Add item</button>} /><section className="payroll-control-grid">{benefits.map((item) => { const employee = item.employeeId === "all" ? "All employees" : employees.find((person) => person.id === item.employeeId)?.name ?? "Unknown employee"; return <article key={item.id}><header><span>{item.kind}</span><button className="icon-button" type="button" onClick={() => setBenefits((current) => current.map((benefit) => benefit.id === item.id ? { ...benefit, active: !benefit.active } : benefit))}>{item.active ? <Pause size={14} /> : <Play size={14} />}</button></header><strong>{item.name}</strong><p>{employee}</p><div><span><small>Employee</small><strong>{money(item.employeeAmount)}</strong></span><span><small>Employer</small><strong>{money(item.employerAmount)}</strong></span></div><footer><small>{item.recurring ? "Recurring" : "One time"} · {item.active ? "Active" : "Paused"}</small><button className="icon-button danger" type="button" onClick={() => setBenefits((current) => current.filter((benefit) => benefit.id !== item.id))}><Trash2 size={14} /></button></footer></article>; })}</section>{modal === "benefit" && <BenefitModal employees={employees} onClose={() => setModal(null)} onSubmit={saveBenefit} />}</div>;

  if (view === "reports") { const reports = [{ name: "Payroll summary", description: "Run totals by period and status", rows: [["Run", "Period", "Status", "Gross", "Deductions", "Net"], ...runs.map((item) => [item.id, `${item.start} to ${item.end}`, item.status, item.gross, item.deductions, item.net])] }, { name: "Employee earnings", description: "Earnings and deductions by employee", rows: [["Employee", "Title", "Pay type", "Base rate", "Schedule"], ...employees.map((item) => [item.name, item.title, item.payType, item.rate, item.paySchedule])] }, { name: "Tax liability", description: "Deductions held per payroll run", rows: [["Run", "Payday", "Tax and deductions"], ...runs.map((item) => [item.id, item.payday, item.deductions])] }, { name: "Pay history", description: "Paid and approved payroll history", rows: [["Run", "Status", "Paid date", "Payment method", "Net"], ...runs.map((item) => [item.id, item.status, item.paidDate ?? "", item.paymentMethod ?? "", item.net])] }]; return <div className="payroll-page"><Heading label="Control" title="Payroll reports" description="Export operational payroll reports using the records currently in this workspace." /><section className="payroll-report-grid">{reports.map((report) => <article key={report.name}><span><FileText size={18} /></span><div><strong>{report.name}</strong><p>{report.description}</p></div><button className="secondary-button" type="button" onClick={() => { downloadCsv(`${report.name.toLowerCase().replaceAll(" ", "-")}.csv`, report.rows); addAudit("Payroll report exported", report.name); }}><Download size={15} />Export CSV</button></article>)}</section></div>; }

  if (view === "settings") return <div className="payroll-page"><Heading label="Control" title="Payroll settings" description="Configure payroll calculations, approvals, and payslip defaults." /><form className="payroll-settings-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next: PayrollSettings = { defaultSchedule: String(form.get("defaultSchedule")), overtimeMultiplier: Number(form.get("overtimeMultiplier")), taxRate: Number(form.get("taxRate")), payslipNote: String(form.get("payslipNote")), requireApproval: form.get("requireApproval") === "on", approvalLimit: Number(form.get("approvalLimit")) }; setSettings(next); addAudit("Payroll settings updated", "Payroll configuration"); onNotice("Payroll settings saved."); }}><section><header><Settings2 size={18} /><div><h3>Calculation defaults</h3><p>Applied when new payroll records are prepared.</p></div></header><div className="payroll-settings-grid"><label className="field"><span>Default schedule</span><select name="defaultSchedule" defaultValue={settings.defaultSchedule}>{schedules.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Overtime multiplier</span><input name="overtimeMultiplier" type="number" min="1" step="0.1" defaultValue={settings.overtimeMultiplier} /></label><label className="field"><span>Default tax / withholding %</span><input name="taxRate" type="number" min="0" max="100" step="0.1" defaultValue={settings.taxRate} /></label><label className="field"><span>Approval amount</span><input name="approvalLimit" type="number" min="0" step="1" defaultValue={settings.approvalLimit} /></label><label className="field span-2"><span>Payslip footer note</span><textarea name="payslipNote" defaultValue={settings.payslipNote} /></label><label className="payroll-check"><input name="requireApproval" type="checkbox" defaultChecked={settings.requireApproval} /><span>Require manager approval before a payroll run can be paid</span></label></div></section><footer><button className="primary-button" type="submit"><CheckCircle2 size={16} />Save payroll settings</button></footer></form></div>;

  return <div className="payroll-page"><Heading label="Control" title="Payroll audit history" description="A clear record of payroll actions and changes." action={<button className="secondary-button" type="button" onClick={() => downloadCsv("payroll-audit.csv", [["Date", "Actor", "Action", "Record"], ...audit.map((item) => [item.date, item.actor, item.action, item.record])])}><Download size={15} />Export audit</button>} /><section className="payroll-audit-table">{audit.map((item) => <article key={item.id}><span><ShieldCheck size={16} /></span><div><strong>{item.action}</strong><small>{item.record}</small></div><div><strong>{item.actor}</strong><small>{new Date(item.date).toLocaleString("en-GB")}</small></div></article>)}</section></div>;
}

function ScheduleModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <Modal title="Create pay schedule" subtitle="Define the period and payday used by a payroll group." onClose={onClose}><form className="payroll-quick-form" onSubmit={onSubmit}><label className="field span-2"><span>Schedule name</span><input name="name" required placeholder="e.g. Weekly delivery payroll" /></label><label className="field"><span>Frequency</span><select name="frequency"><option>Weekly</option><option>Bi-weekly</option><option>Semi-monthly</option><option>Monthly</option></select></label><label className="field"><span>Payday</span><input name="payday" type="date" required /></label><label className="field"><span>Period start</span><input name="periodStart" type="date" required /></label><label className="field"><span>Period end</span><input name="periodEnd" type="date" required /></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit"><Plus size={15} />Create schedule</button></div></form></Modal>; }
function BenefitModal({ employees, onClose, onSubmit }: { employees: Employee[]; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <Modal title="Add deduction or benefit" subtitle="Apply the item to one employee or the whole team." onClose={onClose}><form className="payroll-quick-form" onSubmit={onSubmit}><label className="field span-2"><span>Name</span><input name="name" required placeholder="e.g. Transport allowance" /></label><label className="field"><span>Type</span><select name="kind"><option>Deduction</option><option>Benefit</option><option>Allowance</option></select></label><label className="field"><span>Employee</span><select name="employeeId"><option value="all">All employees</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select></label><label className="field"><span>Employee amount</span><input name="employeeAmount" type="number" min="0" step="0.01" defaultValue="0" /></label><label className="field"><span>Employer amount</span><input name="employerAmount" type="number" min="0" step="0.01" defaultValue="0" /></label><label className="payroll-check span-2"><input name="recurring" type="checkbox" defaultChecked /><span>Repeat every pay run</span></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit"><Plus size={15} />Add item</button></div></form></Modal>; }
